17: Add advanced preference sampling methods
jualat/CleanRLHF pull request #51
Opened 2024-12-15 18:49 UTC by flyingpalli

Fixes issue #17 

What?

- add methods for sampling preferences

How?

- add methods in `sac_rlhf.py`
- change `replay_buffer.sample_trajectories` to sample two lists of `mb_size` many trajectories that have the same length
- add methods to calculate disagreement and entropy in `reward_net.py` (cf. [pebble implementation](https://github.com/rll-research/BPref/blob/main/reward_model.py#L559))

Ready to merge?

- [x] Linter passes
- [x] PR approved

2024-12-16 01:28 UTC, flyingpalli commented
I am just noticing that the sampling from the replay buffer is still far from perfect:
Notice, that each row of `rb.dones` consists of `num_envs` many entries.

Previously, we used to let sampled trajectories be a sequence of rows where only the first and the last row could have 1 as an entry in `dones`. This happend without taking into consideration, in which column (i.e. environment) the `done` occured and let to trajectories being very short.

With the present implementation, we let trajectories be sequences _of fixed length_ which are determined by only applying the previous condition to one column (i.e. there exists one column where the trajectory is the beginning of an observation after a reset). This allows for having `2*mb_size` many trajectories with the same length.

Unfortunately though, now there can be columns in the trajectory where the observation is interrupted by a reset.

I made some runs on 16/12/2024 which can be found in this project's [wandb](https://wandb.ai/cleanRLHF) and I find the progress in the first 40k steps to be sufficient but I can't explain the sharp and irretrievable drop in return after ~45k steps, which is why I write this comment.

2024-12-17 10:44 UTC, bkuen commented on framework/sac_rlhf.py
> +            probs.append(reward_net.preference_prob_hat_member(traj_1, traj_2, member))
This must be `reward_net.preference_hat_entropy_member(traj_1, traj_2, member)`,

2024-12-17 10:50 UTC, bkuen commented on framework/sac_rlhf.py
> +def uniform_sampling(rb: ReplayBuffer, reward_net: RewardNet):
Consider moving those three files into a seperate file (e.g. sampling.py) to keep the main file clean.

2024-12-17 10:51 UTC, bkuen commented on framework/sac_rlhf.py
> +    disagrees = []
Add `with torch.no_grad():` before for loop to avoid unnecessary calculation of gradients

2024-12-17 10:51 UTC, bkuen commented on framework/sac_rlhf.py
> +    entropies = []
Add `with torch.no_grad():` before for loop to avoid unnecessary calculation of gradients

2024-12-17 10:54 UTC, bkuen requested changes
In general, this seems to be a fine first implementation of sampling. It still offers potential for improvement. I am sure that some for loops could be replaced by larger tensor operations. But let's do that in a separate issue if we experience any preformance bottlenecks.

2024-12-17 12:49 UTC, bkuen submitted a review, later dismissed
Thank you for adjusting the code as suggested. As this adds a lot of additional complexity, I suggest that someone else also takes a look at the code before merging.

2024-12-17 13:28 UTC, jualat approved these changes
Looks good to me. The sampling strategies look like they do what they are supposed to do and the code works as expected for me. Nice work :+1: 
The change of the logging level is also fine.

2024-12-17 13:34 UTC, jualat requested changes
Just a small thing: In `sampling.py` there is the import statement for numpy missing

2024-12-17 13:38 UTC, jualat commented
> Just a small thing: In `sampling.py` there is the import statement for numpy missing

After correcting this the code was running fine for me

2024-12-17 14:09 UTC, jualat approved these changes

2024-12-17 14:13 UTC, merged